version: "3.8"

services:
  mysql:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_personal
    ports:
      - "3306:3306" 