name: CI/CD Spring Boot com Docker Compose

on:
  push:
    branches:
      - main

jobs:
  testing-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: 20
          distribution: temurin

      - name: Iniciar ambiente Docker Compose
        run: docker-compose up -d

      - name: Instalar Dependências
        run: mvn clean install -DskipTests

      - name: Executar Testes
        run: mvn test

      - name: Parar ambiente Docker Compose
        run: docker-compose down
