on:
  push:
    branches:  main

jobs:
  Validate-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Baixa o repositório e dá checkout na branch que o job está rodando
        uses: actions/checkout@v3

      - name: Instala o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Valida cobertura dos testes
        run: mvn clean verify

